server:
  port: 8081
  error:
    include-message: always

spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public
  #Conexion a base de datos--info de heroku
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}?socketTimeout=3
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

